---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mtranter/aurelia
    tag: '6-alpine-2'

inputs:
  - name: source

run:
  path: sh
  args:
    - source/ci/scripts/au-build
