---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mtranter/aurelia
    tag: '6-alpine-2'

outputs:
  - name: bundled

inputs:
  - name: source
  - name: npm-repo-cache
    path: /cache

run:
  path: sh
  args:
    - -exc
    - |
      mkdir -p /bundled/src/scripts /bundled/deploy
      mv cache/node_modules source/src
      cd source/src && au build
      cp ./index.html /bundled/src/
      cp ./scripts/* /bundled/src/scripts
      cp ./../deploy/* /bundled/deploy
