---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mtranter/aurelia
    tag: '6-alpine-2'

inputs:
- name: restored-project

run:
  path: au
  args:
    - build
  dir: restored-project/src
