---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: hashicorp/terraform
    tag: 'light'

inputs:
  - name: bundled

run:
  path: sh
  args:
    - -exc
    - |
      ls
      cd bundled/deploy
      terraform plan
