resources:
  - name: source
    type: git
    source:
      uri: https://github.com/mtranter/cv-overkill-home.git
      branch: master
jobs:
  - name: restore
    plan:
      - get: source
        trigger: true
      - task: restore
        file: source/ci/tasks/restore.yml

  - name: build
    plan:
      - get: source
        trigger: true
        passed: [restore]
      - task: build
        file: source/ci/tasks/build.yml
