resource_types:
  - name: npm-cache
    type: docker-image
    source: {repository: ymedlop/npm-cache-resource, tag: latest}

resources:
  - name: source
    type: git
    source: &repo-source
      uri: https://github.com/mtranter/cv-overkill-home.git
      branch: master
  - name: npm-repo-cache
    type: npm-cache # as defined above
    source:
      <<: *repo-source # the source is the same as the corresponding git resource ...
      paths: # ... except that it's only interested in files listing dependencies
        - src/package.json
jobs:
  - name: cache
    plan:

      - get: source
        trigger: true

      - get: npm-repo-cache

  - name: build
    plan:

      - get: source
        trigger: true
        passed: [cache]

      - get: npm-repo-cache
        passed: [cache]

      - task: run build
        file: source/ci/tasks/build.yml
