resources:
  - name: source
    type: git
    source:
      uri: https://github.com/mtranter/cv-overkill-home.git
      branch: master
jobs:
  - name: Restore & Build
    plan:
      - get: source
        trigger: true
      - task: restore
        file: source/ci/tasks/restore.yml
      - task: build
        file: source/ci/tasks/build.yml
